"""Write the Android launcher icon from the desktop app's design (packaging/make_icon.py):
a white chord diagram on the app's green.

- Android 8+: an adaptive icon (green background + the diagram as a vector), so each
  launcher can mask it to its own shape.
- Android 7: PNGs per screen density, square and round.

Rerun after changing the design in packaging/make_icon.py:

    uv run python android/tools/make_icon.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "packaging"))
import make_icon as desktop  # noqa: E402

RES = ROOT / "android" / "app" / "src" / "main" / "res"
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}

# The adaptive icon's 108 dp canvas: the design's unit square maps onto its middle 72 dp
# (what most launchers show), which keeps the diagram inside the 66 dp safe zone.
OFFSET, SCALE = 18.0, 72.0


def _round(rgba: np.ndarray) -> np.ndarray:
    """The square icon cut to a circle, for launchers that ask for a round one."""
    size = rgba.shape[0]
    n = size * desktop.SUPERSAMPLE
    y, x = (np.mgrid[0:n, 0:n] + 0.5) / n
    inside = ((x - 0.5) ** 2 + (y - 0.5) ** 2 <= 0.25).astype(float)
    mask = inside.reshape(size, desktop.SUPERSAMPLE, size, desktop.SUPERSAMPLE).mean(axis=(1, 3))
    # Fill the rounded square's corners with green first, so the circle has no notches.
    out = rgba.astype(float)
    green = np.array(desktop.GREEN, dtype=float)
    a = out[..., 3:4] / 255
    out[..., :3] = out[..., :3] * a + green * (1 - a)
    out[..., 3] = mask * 255
    return out.astype(np.uint8)


def _d(u: float) -> str:
    return f"{OFFSET + SCALE * u:.2f}"


def _rect(x0: float, y0: float, x1: float, y1: float) -> str:
    return f"M{_d(x0)},{_d(y0)} L{_d(x1)},{_d(y0)} L{_d(x1)},{_d(y1)} L{_d(x0)},{_d(y1)} Z"


def _circle(cx: float, cy: float, r: float) -> str:
    rr = f"{SCALE * r:.2f}"
    return (
        f"M{_d(cx - r)},{_d(cy)} a{rr},{rr} 0 1,0 {2 * SCALE * r:.2f},0 "
        f"a{rr},{rr} 0 1,0 {-2 * SCALE * r:.2f},0 Z"
    )


def foreground_xml() -> str:
    """The same strings, frets and finger dots as desktop.draw, as one vector path."""
    thin = 0.035
    strings = np.linspace(0.27, 0.73, 4)
    parts = [_rect(sx - thin / 2, 0.24, sx + thin / 2, 0.82) for sx in strings]
    for fy in (0.24, 0.43, 0.62, 0.82):
        t = thin * 1.6 if fy == 0.24 else thin
        parts.append(_rect(0.25, fy - t / 2, 0.75, fy + t / 2))
    for sx, fy in ((strings[0], 0.525), (strings[2], 0.335), (strings[3], 0.715)):
        parts.append(_circle(sx, fy, 0.068))
    path = " ".join(parts)
    return (
        "<!-- Generated by android/tools/make_icon.py -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp"\n'
        '    android:viewportWidth="108" android:viewportHeight="108">\n'
        f'    <path android:fillColor="#FFFFFF" android:pathData="{path}" />\n'
        "</vector>\n"
    )


ADAPTIVE = """<!-- Generated by android/tools/make_icon.py -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""


def main() -> None:
    for density, size in DENSITIES.items():
        folder = RES / f"mipmap-{density}"
        folder.mkdir(parents=True, exist_ok=True)
        square = desktop.draw(size)
        (folder / "ic_launcher.png").write_bytes(desktop.png(square))
        (folder / "ic_launcher_round.png").write_bytes(desktop.png(_round(square)))
    (RES / "drawable").mkdir(exist_ok=True)
    (RES / "drawable" / "ic_launcher_foreground.xml").write_text(foreground_xml(), newline="\n")
    anydpi = RES / "mipmap-anydpi-v26"
    anydpi.mkdir(exist_ok=True)
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        (anydpi / name).write_text(ADAPTIVE, newline="\n")
    r, g, b = desktop.GREEN
    (RES / "values" / "ic_launcher_background.xml").write_text(
        "<!-- Generated by android/tools/make_icon.py -->\n<resources>\n"
        f'    <color name="ic_launcher_background">#{r:02X}{g:02X}{b:02X}</color>\n</resources>\n',
        newline="\n",
    )
    print(f"wrote the launcher icon into {RES}")


if __name__ == "__main__":
    main()
